### ISSUE TITLE
Driver Code Error

### ISSUE THREAD

**Issue by ekraus50** [MikeBishop/hubitat-holiday#27]
I am getting the following error when saving Holiday Lighting Manager code.
No signature of method: Script1.definition() is applicable for argument types: (java.util.LinkedHashMap) values: [[name:Holiday Lighting, namespace:evequefou, author:Mike Bishop, ...]] on line 12

LIbrary went in no problem

**Comment by MikeBishop** [comment]
Yes, this is the error that occurs when you attempt to install an app as a driver. Install it as an app.
